### PR TITLE
Update CleverDicts.jl

### PR DESCRIPTION
**Pull request by amburosesekar**
version issue  not working when we use v"1.4.0-rc2.0". its true but consider as false and create/misguide to shows error , when we use optimization. so we update simply
(VersionNumber)(split(string(VERSION),"-")[1]) >= v"1.4.0".

### CODE REVIEW

**Comment by joaquimg** [comment]
Why would one use 1.4.0rc2 instead of 1.4.0 itself?

**Comment by blegat** [comment]
Can't we do something like `VERSION >= v"1.4.0-"

**Comment by amburosesekar** [comment]
> Why would one use 1.4.0rc2 instead of 1.4.0 itself?

The problem is , i have downloaded prerelease version and installed in pc. but this problem happens when i used JuMP optimization for simple optimization task, its shows error "No Close match found --mathOptInterface.Utilities.CleverDicts.State(::Tuple{UInt64,Int64})". so totally confused where the bug present after decode the package , i understood where the problem is persist. in my suggestion used to all julia users, may be syntax simple as @blegat suggestion

**Comment by blegat** [comment]
v"1.4.0-" will not work for versions before the commit changing the behavior in Julia. You should find which commit this is in Julia

**Pull request closed without merging**
