### PR TITLE
Fix return types in model.jl

### PR DESCRIPTION
**Pull request by odow**
Some of these were causing unexpected returns from function calls.

Here was an example:
```Julia
julia> c = MOI.add_constraint(model, MOI.VectorOfVariables(x), MOI.Nonnegatives(2))
MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables,MathOptInterface.Nonnegatives}(2)

julia> MOI.delete(model, c)
Dict{MathOptInterface.ConstraintIndex,String} with 0 entries  # <-- What is this?
```

### CODE REVIEW

**Comment by blegat** [comment]
I'd rather merge https://github.com/jump-dev/MathOptInterface.jl/pull/1245 first or it will create a lot of conflicts

**Comment by odow** [comment]
Is #1245 ready to review?

I needed this for https://github.com/jump-dev/MathOptInterface.jl/pull/1281

**Comment by blegat** [comment]
> Is #1245 ready to review?

Yes :)

**Comment by odow** [comment]
Closing because this was implemented in #1245

**Pull request closed without merging**
