### PR TITLE
Changed attribute from SolveTime to SolveTimeSec

### LINKED ISSUE #914: Rename SolveTime to SolveTimeSec
For consistency with `TimeLimitSec`, and because it's a good idea to include the unit in the name (e.g., to help prevent issues like https://github.com/JuliaOpt/SCS.jl/pull/158).

### PR DESCRIPTION
**Pull request by guilhermebodin**
This closes #914

### CODE REVIEW

**Comment by mlubin** [comment]
Thanks for this. Could you add a deprecation warning using `@deprecate`? We should provide helpful error/deprecation messages when possible.

**Comment by blegat** [comment]
We should probably wait for MOI v0.10

**Comment by matbesancon** [comment]
> We should probably wait for MOI v0.10

if there is a deprecation this is not breaking

**Comment by blegat** [comment]
> if there is a deprecation this is not breaking

Why is that ? DataStructures just did breaking changes with deprecation on a patch release and it affected the users of their dependencies: https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/issues/129
This isn't ideal to cause warning in packages depending on your package.

**Comment by matbesancon** [comment]
using `@deprecate` with the previous syntax allows code which ran on the last version to run on this one, especially when the breaking change is just a name

**Comment by mlubin** [comment]
This change is breaking for solver wrappers. The deprecation works only for
users of MOI.

**Comment by odow** [comment]
Closing in favor of #1303

**Pull request closed without merging**
