### PR TITLE
Add throw_if_scalar_and_constant_not_zero

### PR DESCRIPTION
**Pull request by blegat**
Extracted from https://github.com/jump-dev/MathOptInterface.jl/pull/1287/

### CODE REVIEW

**Comment by blegat** [comment]
It could but then an invalid call would return `nothing` instead of a `MethodError`

**Comment by odow** [comment]
How could it get a method error? And when would a method error be preferable?

**Comment by odow** [comment]
That should be caught at the original caller? We shouldn't rely on this method to throw a method error. It would violate the MethodError principle.

**Comment by blegat** [comment]
Since this is a documented function, the user might call this directly in which case it would get the `MethodError` at the first method called so it agrees with the principle.
I don't think the places where it is called from the MOI source code will ever never hit the `MethodError`.

**Review by odow — APPROVED** [review]

**Pull request merged**
