### PR TITLE
Prep for v1.1.1

### PR DESCRIPTION
**Pull request by odow**
One question: is a new test a patch or minor release?

### CODE REVIEW

**Comment by blegat** [comment]
IIUC, it depends on whether we consider it a new feature or a bug-fix. Since we had to change the docstring of `instantiate`, it might be considered a new feature

**Comment by joaquimg** [comment]
Testing existing functionality could be framed as patch, as bug that was not seen due missing tests...

**Comment by blegat** [comment]
I agree for the testing changes. The contentious one is https://github.com/jump-dev/MathOptInterface.jl/pull/1781

**Comment by odow** [comment]
I think it can be a bug fix. It was an error, now it works, and we probably always intended it to work.

**Pull request merged**
