### PR TITLE
Add support for conflicts in MockOptimizer

### PR DESCRIPTION
**Pull request by dourouc05**

### CODE REVIEW

**Comment by odow** [comment]
Can we test this? I don't remember if there are already tests for conflict status in MOI.Test, if not, we should add some.

**Comment by dourouc05** [comment]
You mean, something like https://github.com/jump-dev/MathOptInterface.jl/blob/master/src/Test/UnitTests/solve.jl#L63, with an infeasible model, `test_model_solution` being replaced by a call to `compute_conflict!` and tests of some attributes? In that case, that might go into another PR, as it's not really related to MockOptimizer.

**Comment by dourouc05** [comment]
I just added a direct test for the new functionality.

**Comment by blegat** [comment]
I understand the need to define `compute_conflict!` but for other attributes, you can use a `UniversalFallback` as inner model.

**Comment by dourouc05** [comment]
Actually, I tried to set attributes like `MOI.ConflictStatus`, but I had messages saying the operation is unsupported. Adding the `get`/`set` methods solved the issue.

**Comment by odow** [comment]
Merging this because I need it to fix https://github.com/jump-dev/MathOptInterface.jl/issues/1203

**Pull request merged**
