### PR TITLE
Test getting CanonicalConstraintFunction

### PR DESCRIPTION
**Pull request by odow**
Bug identified by #1283

### CODE REVIEW

**Comment by blegat** [comment]
What's the bug ?

**Comment by odow** [comment]
There was a method ambiguity.

**Comment by blegat** [comment]
Ambiguity with which method ?

**Comment by odow** [comment]
Here was the original failure: https://github.com/jump-dev/MathOptInterface.jl/runs/3236887235#step:6:342

**Comment by odow** [comment]
Coverage failure is spurious.

**Pull request merged**
