### PR TITLE
[FileFormats.MPS] allow spaces in NAME row

### LINKED ISSUE #2145: Malformed NAME line
```
ERROR: Malformed NAME line: NAME PILOTNOV (PILOTS) INTEGRATED MODEL -- NOVEMBER 1979
```

No error,  if I change the NAME line from `PILOTNOV (PILOTS) INTEGRATED MODEL -- NOVEMBER 1979` to `PILOTNOV`

test code:

```Julia

using Downloads

import MathOptInterface as MOI

function testMPS()
    fn = joinpath(tempdir(), "pilotnov.mps.gz")
    if !isfile(fn)
        Downloads.download("https://raw.githubusercontent.com/coin-or-tools/Data-Netlib/master/pilotnov.mps.gz", fn)
    end
    P = MOI.FileFormats.Model(format=MOI.FileFormats.FORMAT_MPS)
    MOI.read_from_file(P, fn)
    nothing
end

testMPS()

```

### PR DESCRIPTION
**Pull request by odow**
Closes #2145

### CODE REVIEW

**Comment by mlubin** [comment]
Is this a fixed format vs free format issue? Do we support fixed format?

**Comment by odow** [comment]
So far we haven't made an explicit distinction between free and fixed format. The goal has been to be permissive in what we read, and restrictive in what we write. So everything gets written in fixed format where possible (except if there are long variable names).

The NAME row is pretty underspecified amongst solvers. They generally just say it's `NAME` followed by the name. I don't know why I originally enforced no spaces.

**Comment by mlubin** [comment]
Sounds fine to allow spaces in names. More generally, IIRC there are cases where you really need to know that you're parsing a fixed format file. They occur only for very old benchmark files. QPSReader has an option to force fixed format.

**Comment by odow** [comment]
> More generally, IIRC there are cases where you really need to know that you're parsing a fixed format file. They occur only for very old benchmark files. QPSReader has an option to force fixed format.

I've been waiting for someone to complain or ask for this, but they haven't yet. It's just a matter of changing this line:

https://github.com/jump-dev/MathOptInterface.jl/blob/0adae07ae14d0eb78ee172d9b23aaca3e32dd664/src/FileFormats/MPS/MPS.jl#L1134-L1135

**Pull request merged**
