### PR TITLE
[Utilities] Fix method invalidation

### PR DESCRIPTION
**Pull request by odow**
The existing method was pretty terrible for inference.

### CODE REVIEW

**Comment by blegat** [comment]
So if I understand correctly:
```julia
Base.promote_rule(::Type{F}, ::Type{T}) where {T,F<:TypedScalarLike{T}} = F
```
is bad,
```julia
Base.promote_rule(::Type{F}, ::Type{T}) where {T,F<:MOI.ScalarAffineFunction{T}} = F
```
is bad but
```julia
Base.promote_rule(::Type{MOI.ScalarAffineFunction{T}}, ::Type{T}) where {T} = MOI.ScalarAffineFunction{T}
```
is good ?

**Comment by odow** [comment]
The underlying issue is
```Julia
julia> Union{} <: MOI.Utilities.TypedScalarLike{Float64}
true
```
which conflicts with
```julia
julia> @which promote_type(Union{}, Float64)
promote_type(::Type{Union{}}, ::Type{T}) where T in Base at promotion.jl:224
```

**Comment by odow** [comment]
Why do we even need these methods? Coverage didn't hit them.

**Comment by blegat** [comment]
I see, I didn't think about `Union{}` ^^

> Why do we even need these methods? Coverage didn't hit them.

Maybe because they are inlined ? I don't remember why they were added though.

**Comment by odow** [comment]
Let's see if anything breaks.

**Comment by odow** [comment]
I guess that's a false negative on the codecov then!

**Pull request merged**
