### PR TITLE
Indexing performance + lazy dense dicts

### PR DESCRIPTION
**Pull request by joaquimg**
Follows: #1129 

This avoids the conversion from dense dict to standard dict in copy functions.

### CODE REVIEW

**Comment by blegat** [comment]
I remember we hesitated between adding a dict in DenseDict or using DenseDict inside a CleverDict to switch from DenseDict to Dict in case of deletion. I thought we decided the second one but I don't remember the details

**Comment by blegat** [comment]
I think we should
1) replace the vector by a DenseDict in CleverDict
2) add the possibility to add a new contiguous index to DenseDict
3) implement setindex! for CleverDict similarly to this PR

**Comment by joaquimg** [comment]
> I remember we hesitated between adding a dict in DenseDict or using DenseDict inside a CleverDict to switch from DenseDict to Dict in case of deletion. I thought we decided the second one but I don't remember the details

I think we only hesitated because it could be too similar to CleverDict.

**Comment by joaquimg** [comment]
We need to be careful with CleverDict because of the downstream usage.
We need to check if theses changes will be breaking.

**Comment by joaquimg** [comment]
one problem is that:
CleverDicts requires the methods `index_to_key` and `key_to_index`
https://github.com/jump-dev/MathOptInterface.jl/blob/746b2e101728724f47402838630e921f2917b677/src/Utilities/CleverDicts.jl#L9

As methods to be overloaded, while DenseDicts get `hash` and `inverse_hash` in the type constructor.
This would be breaking for solvers like GLPK that overload the CleverDict methods:

https://github.com/jump-dev/GLPK.jl/blob/41e649cd81864e90065ac78f42317edcebcd9951/src/MOI_wrapper/MOI_wrapper.jl#L34

**Comment by blegat** [comment]
We could use these functions as default for the map and inverse map of DenseDict so that it is non-breaking

**Comment by odow** [comment]
It is a bit confusing that we have so many types of dictionaries. It's probably okay to get some performance improvement for now, but at some point I'd like to go through and tidy up a lot of this.

**Comment by joaquimg** [comment]
So instead of adding a DenseDict inside CleverDict I will merge the two of them.
As @blegat that can be done without breaking. And DenseDict was never released anyway.

**Comment by blegat** [comment]
Merging them sounds good

**Comment by blegat** [comment]
@joaquimg Is this closed by https://github.com/jump-dev/MathOptInterface.jl/pull/1142 ?

**Pull request closed without merging**
