### PR TITLE
Parametrize GenericModel with objective/variable sub-model

### PR DESCRIPTION
**Pull request by blegat**
Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1261
Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1502
Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1470

### CODE REVIEW

**Comment by odow** [comment]
Not sure why ci didn't start?

**Review by odow — COMMENTED** [review]
See the test failures.

**Comment by odow** [comment]
Actually I should be able to handle this.

**Comment by odow** [comment]
That type printing is now pretty terrible...

**Comment by blegat** [comment]
> That type printing is now pretty terrible...

It shouldn't be an issue thanks to https://github.com/JuliaLang/julia/pull/36107.
It's not visible in the docs since it's using Julia v1.0. We probably also need to export `Model` for it to work :/

**Comment by blegat** [comment]
With the added export, you now have
```julia
julia> Model
ERROR: UndefVarError: Model not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:26
 [2] top-level scope
   @ REPL[3]:1
julia> Base.show(IOContext(stdout, :compact => true), MathOptInterface.Utilities.Model)
Model{T} where T
julia> Base.show(MathOptInterface.Utilities.Model)
MathOptInterface.Utilities.Model{T} where T
julia> print(MathOptInterface.Utilities.Model)
MathOptInterface.Utilities.Model{T} where T
julia> MathOptInterface.Utilities.Model
MathOptInterface.Utilities.Model{T} where T (alias for MathOptInterface.Utilities.GenericModel{T, MathOptInterface.Utilities.ObjectiveFunctionContainer{T}, MathOptInterface.Utilities.SingleVariableConstraints{T}, MathOptInterface.Utilities.ModelFunctionConstraints{T}} where T)

julia> using MathOptInterface.Utilities

julia> Model
Model{T} where T (alias for MathOptInterface.Utilities.GenericModel{T, MathOptInterface.Utilities.ObjectiveFunctionContainer{T}, MathOptInterface.Utilities.SingleVariableConstraints{T}, MathOptInterface.Utilities.ModelFunctionConstraints{T}} where T)
```

**Comment by odow** [comment]
My main issue is that it's going to cause issues with JuMP's printing of a model. Perhaps we could modify the printing on the JuMP-side though.

**Review by odow — APPROVED** [review]

**Pull request merged**
